{"name": "test_order_detail[data0]", "status": "broken", "statusDetails": {"message": "ValueError: substring not found", "trace": "@pytest.fixture(scope='session')\n    def login_token():\n        data = yaml_util.extract_case('user_center.yaml', 'user_login')\n>       result = api_service.handle_case(data[0])\n\n..\\conftest.py:9: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\core\\ApiService.py:29: in handle_case\n    case_info = self.extract.extract_case(case_info)\n..\\..\\utils\\ExtractUtil.py:57: in extract_case\n    data = self.process_data(str_case_info)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <utils.ExtractUtil.ExtractUtil object at 0x000001790798B7C8>\ndata = '{\"json\": {\"username\": \"17621947777\", \"password\": \"123456\"}}'\n\n    def process_data(self, data):\n        if \"${\" and \"}\" in data:\n>           start_index = data.index('${')\nE           ValueError: substring not found\n\n..\\..\\utils\\ExtractUtil.py:41: ValueError"}, "start": 1713508337686, "stop": 1713508337686, "uuid": "bf3a0dfe-c398-4ac0-a13f-6eaac8f58e44", "historyId": "621c04dabf39f9da96e610aac6728259", "testCaseId": "b3b8f7bf93c9bf014f3851168d51cf02", "fullName": "testcases.ordercenter.test_order.TestOrder#test_order_detail", "labels": [{"name": "story", "value": "登录接口"}, {"name": "feature", "value": "用户订单模块"}, {"name": "parentSuite", "value": "testcases.ordercenter"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrder"}, {"name": "host", "value": "WIN-20231207OXO"}, {"name": "thread", "value": "8332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.ordercenter.test_order"}]}